import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { ProblemMap } from "~/components/problem-map";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>AlgoHelper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="flex flex-col items-center gap-4">
            <h1 className="text-4xl font-bold">Welcome to AlgoHelper</h1>
            <p className="text-lg text-center">
              A platform to help you learn and practice algorithms and data structures
            </p>
            <ProblemMap />
          </div>
        </div>
      </main>
    </>
  );
}

