import Head from "next/head";
import { LoadingSkeleton } from "~/components/loader";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table";
import { api } from "~/utils/api";

export default function ProblemPage() {
  const { data, isLoading, error } = api.layout.getProblemMap.useQuery();

  if (isLoading) return <LoadingSkeleton />;
  if (error) return <div>Error loading problems</div>;
  if (!data) return <div>Error loading problems</div>;

  return (
    <>
      <Head>
        <title>AlgoHelper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center px-4">
        <div className="container flex flex-col items-center justify-center gap-6 py-8">
          <h1 className="text-3xl font-bold text-center">foo</h1>
          <p className="text-base text-center max-w-md">
            A platform to help you learn and practice algorithms and data structures.
          </p>
        </div>
        <div className="w-full max-w-3xl">
          <Table>
            <TableCaption>A list of your recent invoices.</TableCaption>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[80px]">Invoice</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Method</TableHead>
                <TableHead className="text-right">Amount</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">INV001</TableCell>
                <TableCell>Paid</TableCell>
                <TableCell>Credit Card</TableCell>
                <TableCell className="text-right">$250.00</TableCell>
              </TableRow>
              {/* Add more rows as needed */}
            </TableBody>
          </Table>
        </div>
      </main>
    </>
  );
}
