import Head from 'next/head';
import { useRouter } from 'next/router';
import { api } from '~/utils/api';
import Welcome from "~/solutions/welcome.mdx";
import dynamic from 'next/dynamic';

export default function SolutionPage() {
  const router = useRouter();
  const { problem, solution } = router.query;

  const { data, isLoading, error } = api.layout.getProblemMap.useQuery();
  const MDXContent = dynamic(
    () => import(`~/solutions/${solution?.toString()}.mdx`)
      .catch(() => import(`~/solutions/fallback.mdx`)));

  return (
    <>
      <Head>
        <title>AlgoHelper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center px-4 py-8">
        <div className="container flex flex-col items-center justify-center gap-4 py-8">
          <div className="flex flex-col height-fit">
            <MDXContent />
          </div>
        </div>
      </main >
    </>
  );

}

